spring:
  application:
    name: photoprocessingservice

server:
  port: 8080
  servlet:
    contextPath: /photoprocessingservice

user:
  timezone: UTC

hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true

logging:
  level:
    web: DEBUG