DELETE FROM "PUBLIC"."PHOTOS_TAG";
DELETE FROM "PUBLIC"."TAG";
DELETE FROM "PUBLIC"."PHOTOS";
DELETE FROM "SYSTEM_LOB_STREAM";

-- ALTER TABLE SYSTEM_LOB_STREAM DROP CONSTRAINT IF EXISTS SYSTEM_LOB_STREAM_PRIMARY_KEY;

